*  DSC 530
*  Weeks 3 & 4
*  Doug Nolan

# Week 3, Exercise 4

In [1]:
import random
import pandas
random.seed(0)
salaries = [round(random.random()*1000000, -3) for _ in range(100)]

# Exercise 5

### Using the data from exercise 4, calculate the following statistics without importing anything from the statistics module in the Python standard library, and then confirm your results match up to those that are obtained when using the statistics module (where possible):

In [2]:
# mean calculation
n = len(salaries)
mean = sum(salaries) / n

print(mean)

# median calculation
sorted_data = sorted(salaries)
if n % 2 == 0:
    median = (sorted_data[n//2-1] + sorted_data[n//2]) / 2
else:
    median = sorted_data[n//2]

print(median)

# mode
mode = max(set(salaries), key=salaries.count)
print(mode)

# sample variance
variance = sum((x - mean) ** 2 for x in salaries) / (n-1)
print(variance)

# sample standard deviation
std_dev = variance ** 0.5
print(std_dev)

585690.0
589000.0
477000.0
70664054444.44444
265827.11382484

In [3]:
import statistics as stats

print(
    stats.mean(salaries),
    stats.median(salaries),
    stats.mode(salaries),
    stats.variance(salaries),
    stats.stdev(salaries)
)

585690.0 589000.0 477000.0 70664054444.44444 265827.11382484

# Exercise 6

In [4]:
# range
data_range = max(salaries) - min(salaries)

# coefficient of variation
cv = stats.stdev(salaries) / stats.mean(salaries)

# quartiles
q1 = stats.quantiles(salaries, n=4)[0]
q3 = stats.quantiles(salaries, n=4)[2]

# interquartile range
iqr = q3 - q1

# quartile coefficient of dispersion
qcd = (q3 - q1) / (q3 + q1)

print(data_range, cv, iqr, qcd)

995000.0 0.45386998894439035 421750.0 0.34491923941934166

# Exercise 7

In [5]:
# min max scaling
min_val = min(salaries)
max_val = max(salaries)

normalized = [(x - min_val) / (max_val - min_val) for x in salaries]

# standarization (z score)
mean = sum(salaries) / n
std_dev = (sum((x - mean) ** 2 for x in salaries) / (n-1)) ** 0.5

standardized = [(x - mean) / std_dev for x in salaries]

print(normalized)
print(standardized)

[0.8472361809045226, 0.7608040201005025, 0.4221105527638191, 0.2592964824120603, 0.5125628140703518, 0.40603015075376886, 0.7869346733668342, 0.3035175879396985, 0.47839195979899496, 0.5849246231155779, 0.9115577889447236, 0.5065326633165829, 0.28241206030150756, 0.7587939698492462, 0.6201005025125628, 0.25125628140703515, 0.91356783919598, 0.9869346733668342, 0.8130653266331658, 0.9055276381909547, 0.31055276381909547, 0.7326633165829146, 0.9025125628140703, 0.6864321608040201, 0.4733668341708543, 0.10050251256281408, 0.43517587939698493, 0.6130653266331658, 0.9165829145728643, 0.9708542713567839, 0.47839195979899496, 0.8683417085427135, 0.26030150753768844, 0.8080402010050252, 0.5507537688442211, 0.01306532663316583, 0.7226130653266332, 0.4, 0.828140703517588, 0.6703517587939698, 0.0, 0.49547738693467336, 0.871356783919598, 0.2442211055276382, 0.3256281407035176, 0.8733668341708543, 0.19095477386934673, 0.5698492462311557, 0.23919597989949748, 0.9718592964824121, 0.8060301507537688, 0.4492462311557789, 0.07939698492462312, 0.32060301507537686, 0.5095477386934674, 0.9366834170854271, 0.10854271356783919, 0.5527638190954773, 0.7095477386934673, 0.5487437185929648, 0.8170854271356784, 0.5417085427135678, 0.9678391959798995, 0.6050251256281407, 0.5899497487437186, 0.4462311557788945, 0.5979899497487438, 0.385929648241206, 0.5778894472361809, 0.2904522613065327, 0.18894472361809045, 0.18693467336683417, 0.6150753768844222, 0.6592964824120603, 0.47839195979899496, 0.08944723618090453, 0.7608040201005025, 0.8804020100502512, 0.9266331658291457, 0.8452261306532663, 0.9015075376884422, 0.9266331658291457, 0.542713567839196, 0.39195979899497485, 0.7075376884422111, 0.27638190954773867, 0.8150753768844221, 0.8522613065326633, 0.8984924623115578, 0.5919597989949749, 0.9537688442211055, 0.5819095477386935, 0.45226130653266333, 0.6623115577889447, 1.0, 0.9206030150753769, 0.7959798994974875, 0.0814070351758794, 0.6150753768844222, 0.48743718592964824]
[0.9717217942267801, 0.6482032533127501, -0.6195380058503674, -1.228956652688424, -0.28097209094033604, -0.6797275018343729, 0.7460111842867592, -1.0634355387324086, -0.40887476990634786, -0.010119359012310937, 1.2124797781628023, -0.3035431519343381, -1.142434252211416, 0.6406795663147493, 0.12154516345270126, -1.2590514006804265, 1.220003465160803, 1.4946180405878284, 0.8438191152607681, 1.1899087171688003, -1.037102634239406, 0.5428716353407403, 1.178623186671799, 0.36982683438672426, -0.4276839874013496, -1.8233279255304788, -0.5706340403633628, 0.09521225895969881, 1.2312889956578041, 1.434428544603823, -0.40887476990634786, 1.0507205077057873, -1.2251948091894236, 0.8250098977657664, -0.1380220379783228, -2.150608309943509, 0.5052532003507368, -0.7022985628283751, 0.9002467677457734, 0.3096373384027187, -2.199512275430514, -0.34492343042334195, 1.0620060382027885, -1.285384305173429, -0.9806749817544008, 1.0695297252007891, -1.4847620106204475, -0.06654701149731616, -1.304193522668431, 1.4381903881028233, 0.8174862107677657, -0.517968231377358, -1.9023266390094862, -0.9994841992494026, -0.2922576214373371, 1.3065258656378111, -1.7932331775384762, -0.1304983509803221, 0.4563492348637323, -0.14554572497632348, 0.8588664892567696, -0.17187862946932592, 1.4231430141068218, 0.06511751096769604, 0.008689858482690806, -0.529253761874359, 0.038784606474693596, -0.7549643718143799, -0.03645226350531338, -1.112339504219413, -1.4922856976184482, -1.4998093846164489, 0.10273594595769951, 0.26825705991371485, -0.40887476990634786, -1.8647082040194827, 0.6482032533127501, 1.0958626296937914, 1.2689074306478076, 0.9641981072287793, 1.1748613431727988, 1.2689074306478076, -0.16811678597032556, -0.7323933108203778, 0.4488255478657316, -1.165005313205418, 0.8513428022587689, 0.9905310117217818, 1.1635758126757978, 0.016213545480691503, 1.370477205120817, -0.02140488950931198, -0.5066827008803569, 0.2795425904107159, 1.543522006074833, 1.2463363696538055, 0.7798677757777622, -1.8948029520114855, 0.10273594595769951, -0.37501817841534474]

# Exercise 8

In [6]:
# covariance of standardized data
covariance = sum(
    (standardized[i] - sum(standardized)/n) * 
    (normalized[i] - sum(normalized)/n)
    for i in range(n)
) / (n - 1)

# pearson correlation
std_std = (sum((x - sum(standardized)/n)**2 for x in standardized) / (n-1)) **0.5
std_norm = (sum((x - sum(normalized)/n)**2 for x in normalized) / (n-1)) **0.5

correlation = covariance / (std_std * std_norm)

print(covariance, correlation)

0.2671629284671759 1.0

# Chapter 2
## Exercise 1

In [7]:
import pandas as pd
df = pd.read_csv("Bellevue/dsc530/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/ch_02/data/parsed.csv")
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California

In [8]:
japan_mb = df[(df["place"].str.contains("Japan")) & (df["magType"] == "mb")]
percentile_95 = japan_mb["mag"].quantile(0.95)

print(percentile_95)

4.9

# Exercise 2

In [9]:
indo = df[df["place"].str.contains("Indonesia")]

tsunami_pct = indo["tsunami"].mean() * 100

print(tsunami_pct)

23.12925170068027

# exercise 3

In [10]:
nevada = df[df["place"].str.contains("Nevada")]
# summary stats
print(nevada.describe())

             cdi        dmin       felt         gap         mag   mmi  \
count  15.000000  677.000000  15.000000  677.000000  677.000000  1.00
mean    2.440000    0.166982   2.400000  154.029527    0.491728  2.84
std     0.501142    0.166400   4.626013   68.769713    0.689560   NaN
min     2.000000    0.001000   1.000000   29.140000   -0.500000  2.84
25%     2.000000    0.054000   1.000000   97.670000   -0.100000  2.84
50%     2.200000    0.113000   1.000000  149.550000    0.400000  2.84
75%     2.900000    0.234000   1.000000  200.470000    0.900000  2.84
max     3.300000    1.414000  19.000000  355.910000    2.900000  2.84

              nst         rms         sig          time  tsunami     tz  \
count  677.000000  677.000000  677.000000  6.770000e+02    677.0  677.0
mean    12.608567    0.151909   10.688331  1.538314e+12      0.0 -480.0
std      9.890620    0.084742   19.252727  5.954070e+08      0.0    0.0
min      3.000000    0.000500    0.000000  1.537247e+12      0.0 -480.0
25%      6.000000    0.106900    0.000000  1.537854e+12      0.0 -480.0
50%      9.000000    0.146300    2.000000  1.538280e+12      0.0 -480.0
75%     16.000000    0.186700   12.000000  1.538821e+12      0.0 -480.0
max     61.000000    0.863400  129.000000  1.539461e+12      0.0 -480.0

            updated
count  6.770000e+02
mean   1.538402e+12
std    6.000267e+08
min    1.537307e+12
25%    1.537928e+12
50%    1.538428e+12
75%    1.538878e+12
max    1.539483e+12

# exercise 4

In [14]:
# define ring of fire locations
ring_of_fire_locations = [
    "Alaska", "Antarctic", "Bolivia", "California", "Canada", "Chile",
    "Costa Rica", "Ecuador", "Fiji", "Guatemala", "Indonesia", "Japan",
    "Kermadec Islands", "Mexico", "New Zealand", "Peru",
    "Philippines", "Russia", "Taiwan", "Tonga", "Washington"
]

df["ring_of_fire"] = df["place"].apply(
    lambda x: any(loc in x for loc in ring_of_fire_locations)
)

df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,time,title,tsunami,type,types,tz,updated,url,parsed_place,ring_of_fire
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California,False
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California,False
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California,False
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California,False
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California,False

# exercise 5

In [15]:
counts = df["ring_of_fire"].value_counts()

print(counts)

ring_of_fire
False    4905
True     4427
Name: count, dtype: int64

## 4427 earthquakes happened inside the ring of fire
## 4905 earthquakes happened outside the ring of fire

# exercise 6

In [16]:
rof_tsunamis = df[df["ring_of_fire"] == True]["tsunami"].sum()


print(rof_tsunamis)

43