*  DSC 530
*  Weeks 1 & 2
*  Doug Nolan

# Week 1, Exercise 1

We want to look at data for the Facebook, Apple, Amazon, Netflix, and Google (FAANG) stocks, but we were given each as a separate CSV file (obtained using the stock_analysis package we will build in Chapter 7, Financial Analysis – Bitcoin and the Stock Market). Combine them into a single file and store the dataframe of the FAANG data as faang for the rest of the exercises:

Read in the aapl.csv, amzn.csv, fb.csv, goog.csv, and nflx.csv files.
Add a column to each dataframe, called ticker, indicating the ticker symbol it is for (Apple's is AAPL, for example); this is how you look up a stock. In this case, the filenames happen to be the ticker symbols.
Append them together into a single dataframe.
Save the result in a CSV file called faang.csv

In [1]:
import pandas as pd

In [2]:
# 1a. Read in the aapl.csv, amzn.csv, fb.csv, goog.csv, and nflx.csv files.
aapl = pd.read_csv("Bellevue/dsc530/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/ch_07/data/apple.csv")
amzn = pd.read_csv("Bellevue/dsc530/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/ch_07/data/amazon.csv")
fb = pd.read_csv("Bellevue/dsc530/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/ch_07/data/facebook.csv")
goog = pd.read_csv("Bellevue/dsc530/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/ch_07/data/google.csv")
nflx = pd.read_csv("Bellevue/dsc530/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/ch_07/data/netflix_jan_2021.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Bellevue/dsc530/Hands-On-Data-Analysis-with-Pandas-2nd-edition-master/ch_07/data/apple.csv'

In [4]:
# 1b. Add a column to each dataframe, called ticker, indicating the ticker symbol it is for (Apple's is AAPL, for example);
# this is how you look up a stock. In this case, the filenames happen to be the ticker symbols.
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'
nflx['ticker'] = 'NFLX'

In [5]:
# 1c. Append them together into a single dataframe.
faang = pd.concat([aapl, amzn, fb, goog, nflx], ignore_index=True)

In [6]:
# 1d. d) Save the result in a CSV file called faang.csv.
faang.to_csv('faang.csv', index=False)
faang.head()

,date,high,low,open,close,volume,adj_close,ticker
0,2019-01-02,39.712502,38.557499,38.722500,39.480000,148158800.0,38.562561,AAPL
1,2019-01-03,36.430000,35.500000,35.994999,35.547501,365248800.0,34.721451,AAPL
2,2019-01-04,37.137501,35.950001,36.132500,37.064999,234428400.0,36.203678,AAPL
3,2019-01-07,37.207500,36.474998,37.174999,36.982498,219111200.0,36.123104,AAPL
4,2019-01-08,37.955002,37.130001,37.389999,37.687500,164101200.0,36.811718,AAPL

# Exercise 2

With faang, use type conversion to cast the values of the date column into datetimes and the volume column into integers. Then, sort by date and ticker.

In [7]:
# make sure date and volumes are expected data types and then sort by date.
faang['date'] = pd.to_datetime(faang['date'])
faang['volume'] = faang['volume'].astype(int)

faang = faang.sort_values(by=['date', 'ticker'])
faang.head()

,date,high,low,open,close,volume,adj_close,ticker
0,2019-01-02,39.712502,38.557499,38.722500,39.480000,148158800,38.562561,AAPL
505,2019-01-02,1553.359985,1460.930054,1465.199951,1539.130005,7983100,1539.130005,AMZN
1010,2019-01-02,137.509995,128.559998,128.990005,135.679993,28146200,135.679993,FB
1514,2019-01-02,1052.319946,1015.710022,1016.570007,1045.849976,1532600,1045.849976,GOOG
1,2019-01-03,36.430000,35.500000,35.994999,35.547501,365248800,34.721451,AAPL

# Exercise 3

In [8]:
#Find the seven rows in faang with the lowest value for volume.
lowest_volume = faang.nsmallest(7, 'volume')
lowest_volume

,date,high,low,open,close,volume,adj_close,ticker
2014,2020-12-24,1746.000000,1729.109985,1735.000000,1738.849976,346800,1738.849976,GOOG
1761,2019-12-24,1350.260010,1342.780029,1348.500000,1343.560059,347500,1343.560059,GOOG
1744,2019-11-29,1310.204956,1303.969971,1307.119995,1304.959961,587000,1304.959961,GOOG
1762,2019-12-26,1361.327026,1344.469971,1346.170044,1360.400024,667500,1360.400024,GOOG
1583,2019-04-11,1207.959961,1200.130005,1203.959961,1204.619995,710200,1204.619995,GOOG
1582,2019-04-10,1203.785034,1196.435059,1200.680054,1202.160034,724600,1202.160034,GOOG
1674,2019-08-21,1199.000000,1187.430054,1193.150024,1191.250000,740700,1191.250000,GOOG

# Exercise 4
#### Right now, the data is somewhere between long and wide format. Use melt() to make it completely long format. Hint: date and ticker are our ID variables (they uniquely identify each row). We need to melt the rest so that we don't have separate columns for open, high, low, close, and volume.

In [9]:
# turn data into long skinny columns instead of multiple rows 
faang_long = pd.melt(
    faang,
    id_vars=['date', 'ticker'],
    var_name='variable',
    value_name='value')

faang_long.head()

        date ticker variable        value
0 2019-01-02   AAPL     high    39.712502
1 2019-01-02   AMZN     high  1553.359985
2 2019-01-02     FB     high   137.509995
3 2019-01-02   GOOG     high  1052.319946
4 2019-01-03   AAPL     high    36.430000

# Exercise 5.
#### Suppose we found out that on July 26, 2018 there was a glitch in how the data was recorded. How should we handle this? Note that there is no coding required for this exercise.

In [13]:
#handle the data glitch
# there's a glitch in the system

## option 1 - remove rows - if the data is unreliable one option is to remove the impacted rows of data
## option 2 - impute values - use interpolation of nearby dates and add values to the missing / impacted data

# Exercise 6
#### do these things
1. Read in the covid19_cases.csv file. 
2. Create a date column using the data in the dateRep column and the pd.to_datetime() function.
3. Set the date column as the index and sort the index.
4. Replace all occurrences of United_States_of_America and United_Kingdom with USA and UK, respectively. Hint: the replace() method can be run on the dataframe as a whole.
5. Using the countriesAndTerritories column, filter the cleaned COVID-19 cases data down to Argentina, Brazil, China, Colombia, India, Italy, Mexico, Peru, Russia, Spain, Turkey, the UK, and the USA.
6. Pivot the data so that the index contains the dates, the columns contain the country names, and the values are the case counts (the cases column). Be sure to fill in NaN values with 0.

In [18]:
#read pesky excel file, not CSV
covid = pd.read_excel('Bellevue/dsc530/COVID-19-geographic-disbtribution-worldwide-2020-12-14.xlsx')

covid.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,2020-12-14,14,12,2020,746,6,Afghanistan,AF,AFG,38041757.0,Asia,9.013779
1,2020-12-13,13,12,2020,298,9,Afghanistan,AF,AFG,38041757.0,Asia,7.052776
2,2020-12-12,12,12,2020,113,11,Afghanistan,AF,AFG,38041757.0,Asia,6.868768
3,2020-12-11,11,12,2020,63,10,Afghanistan,AF,AFG,38041757.0,Asia,7.134266
4,2020-12-10,10,12,2020,202,16,Afghanistan,AF,AFG,38041757.0,Asia,6.968658

In [19]:
# ensure date datatype is compatible for sorting
covid['date'] = pd.to_datetime(covid['dateRep'], dayfirst=True)

covid = covid.set_index('date').sort_index()

covid = covid.replace({
    'United_States_of_America': 'USA',
    'United_Kingdom': 'UK'})

covid.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
date,,,,,,,,,,,,
2019-12-31,2019-12-31,31,12,2019,0,0,Iraq,IQ,IRQ,39309789.0,Asia,NaN
2019-12-31,2019-12-31,31,12,2019,0,0,Netherlands,NL,NLD,17282163.0,Europe,NaN
2019-12-31,2019-12-31,31,12,2019,0,0,Israel,IL,ISR,8519373.0,Asia,NaN
2019-12-31,2019-12-31,31,12,2019,0,0,New_Zealand,NZ,NZL,4783062.0,Oceania,NaN
2019-12-31,2019-12-31,31,12,2019,0,0,Dominican_Republic,DO,DOM,10738957.0,America,NaN

In [20]:
#drill down to specific countries only
countries = [
    'Argentina', 'Brazil', 'China', 'Columbia', 'India', 'Italy', 'Mexico', 'Peru',
    'Russia', 'Spain', 'Turkey', 'UK', 'USA']

covid_filtered = covid[covid['countriesAndTerritories'].isin(countries)]
covid_filtered.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
date,,,,,,,,,,,,
2019-12-31,2019-12-31,31,12,2019,0,0,USA,US,USA,329064917.0,America,NaN
2019-12-31,2019-12-31,31,12,2019,0,0,Brazil,BR,BRA,211049519.0,America,NaN
2019-12-31,2019-12-31,31,12,2019,0,0,Spain,ES,ESP,46937060.0,Europe,NaN
2019-12-31,2019-12-31,31,12,2019,0,0,Italy,IT,ITA,60359546.0,Europe,NaN
2019-12-31,2019-12-31,31,12,2019,0,0,Russia,RU,RUS,145872260.0,Europe,NaN

In [21]:
#pivot with only the selected countries
covid_pivot = covid_filtered.pivot_table(
    index='date',
    columns='countriesAndTerritories',
    values='cases',
    fill_value=0)

covid_pivot.head()

countriesAndTerritories,Argentina,Brazil,China,India,Italy,Mexico,Peru,Russia,Spain,Turkey,UK,USA
date,,,,,,,,,,,,
2019-12-31,0.0,0.0,27.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-03,0.0,0.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0