# ============================================
### Title: Assignment 1.2
### Author: Doug Nolan
### Date: 9 June 2026
### Modified By: Doug Nolan
### Description: this program explores pandas dataframe. we grab video game data and play with it. Find some top 5 rows by different columns. replace null values and calculate a median user score
# ============================================

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rush4ratio/video-game-sales-with-ratings")

print("Path to dataset files:", path)

Path to dataset files: /Users/doug/.cache/kagglehub/datasets/rush4ratio/video-game-sales-with-ratings/versions/2

In [17]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("/Users/doug/DSC 550/Video_Games_Sales_as_at_22_Dec_2016.csv")

print(df.head(10))

                        Name Platform  Year_of_Release         Genre  \
0                 Wii Sports      Wii           2006.0        Sports
1          Super Mario Bros.      NES           1985.0      Platform
2             Mario Kart Wii      Wii           2008.0        Racing
3          Wii Sports Resort      Wii           2009.0        Sports
4   Pokemon Red/Pokemon Blue       GB           1996.0  Role-Playing
5                     Tetris       GB           1989.0        Puzzle
6      New Super Mario Bros.       DS           2006.0      Platform
7                   Wii Play      Wii           2006.0          Misc
8  New Super Mario Bros. Wii      Wii           2009.0      Platform
9                  Duck Hunt      NES           1984.0       Shooter

  Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  \
0  Nintendo     41.36     28.96      3.77         8.45         82.53
1  Nintendo     29.08      3.58      6.81         0.77         40.24
2  Nintendo     15.68     12.76      3.79         3.29         35.52
3  Nintendo     15.61     10.93      3.28         2.95         32.77
4  Nintendo     11.27      8.89     10.22         1.00         31.37
5  Nintendo     23.20      2.26      4.22         0.58         30.26
6  Nintendo     11.28      9.14      6.50         2.88         29.80
7  Nintendo     13.96      9.18      2.93         2.84         28.92
8  Nintendo     14.44      6.94      4.70         2.24         28.32
9  Nintendo     26.93      0.63      0.28         0.47         28.31

   Critic_Score  Critic_Count User_Score  User_Count Developer Rating
0          76.0          51.0          8       322.0  Nintendo      E
1           NaN           NaN        NaN         NaN       NaN    NaN
2          82.0          73.0        8.3       709.0  Nintendo      E
3          80.0          73.0          8       192.0  Nintendo      E
4           NaN           NaN        NaN         NaN       NaN    NaN
5           NaN           NaN        NaN         NaN       NaN    NaN
6          89.0          65.0        8.5       431.0  Nintendo      E
7          58.0          41.0        6.6       129.0  Nintendo      E
8          87.0          80.0        8.4       594.0  Nintendo      E
9           NaN           NaN        NaN         NaN       NaN    NaN

In [5]:
print(df.shape)
# there are 16,719 rows and 16 columns in this data
# there are 16.7K video games and we have 16 columns of data on these games

(16719, 16)

In [7]:
# find top 5 games by critic score

df_top_critic = df.sort_values(by= 'Critic_Score', ascending=False)[['Name', 'Platform', 'Critic_Score', 'Global_Sales']]
display(df_top_critic.head(5))

                          Name Platform  Critic_Score  Global_Sales
227   Tony Hawk's Pro Skater 2       PS          98.0          4.68
57         Grand Theft Auto IV      PS3          98.0         10.50
51         Grand Theft Auto IV     X360          98.0         11.01
5350               SoulCalibur       DC          98.0          0.34
165         Grand Theft Auto V     XOne          97.0          5.48

In [8]:
# find the count of games in each genre
genre_count = df['Genre'].value_counts()

print('Games by Genre:')
display(genre_count)

Games by Genre:

Genre
Action          3370
Sports          2348
Misc            1750
Role-Playing    1500
Shooter         1323
Adventure       1303
Racing          1249
Platform         888
Simulation       874
Fighting         849
Strategy         683
Puzzle           580
Name: count, dtype: int64

In [9]:
# find first 5 games in the df on the SNES
snes_games = df[df['Platform'] == 'SNES']
display(snes_games.head(5))

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
18,Super Mario World,SNES,1990.0,Platform,Nintendo,12.78,3.75,3.54,0.55,20.61,NaN,NaN,NaN,NaN,NaN,NaN
56,Super Mario All-Stars,SNES,1993.0,Platform,Nintendo,5.99,2.15,2.12,0.29,10.55,NaN,NaN,NaN,NaN,NaN,NaN
71,Donkey Kong Country,SNES,1994.0,Platform,Nintendo,4.36,1.71,3.00,0.23,9.30,NaN,NaN,NaN,NaN,NaN,NaN
76,Super Mario Kart,SNES,1992.0,Racing,Nintendo,3.54,1.24,3.81,0.18,8.76,NaN,NaN,NaN,NaN,NaN,NaN
137,Street Fighter II: The World Warrior,SNES,1992.0,Fighting,Capcom,2.47,0.83,2.87,0.12,6.30,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# find 5 publisher with the highest global sales - sum function
pub_sales = (
    df.groupby('Publisher')['Global_Sales']
    .sum()
    .sort_values(ascending=False)
)

print('Top 5 Publishers by Total Globabl Sales:')
display(pub_sales.head(5))

Top 5 Publishers by Total Globabl Sales:

Publisher
Nintendo                       1788.81
Electronic Arts                1116.96
Activision                      731.16
Sony Computer Entertainment     606.48
Ubisoft                         471.61
Name: Global_Sales, dtype: float64

In [13]:
# create new column - % of global sales from North America. display first 5 rows of new df
df['NA_Sales_Pct'] = (
    df['NA_Sales'] / df['Global_Sales']) *100

display(
    df[
        ['Name',
         'NA_Sales',
         'Global_Sales',
         'NA_Sales_Pct']
        ].head()
)

                       Name  NA_Sales  Global_Sales  NA_Sales_Pct
0                Wii Sports     41.36         82.53     50.115110
1         Super Mario Bros.     29.08         40.24     72.266402
2            Mario Kart Wii     15.68         35.52     44.144144
3         Wii Sports Resort     15.61         32.77     47.635032
4  Pokemon Red/Pokemon Blue     11.27         31.37     35.926044

In [14]:
# find the count of null entries in each column
missing_values = df.isna().sum()

print('Missing Values in each column:')
display(missing_values)

Missing Values in each column:

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       8582
Critic_Count       8582
User_Score         6704
User_Count         9129
Developer          6623
Rating             6769
NA_Sales_Pct          0
dtype: int64

In [19]:
# caclulate median user score - will get error. find and rplace string with nan and then calculate median. then replace all null with median value
print(df['User_Score'].unique()[:40])
# found a nan and tbd value in here. nan is null - tbd is to be determined . weird rating but whatever

# replace tbd with nan
df['User_score'] = df['User_Score'].replace('tbd', np.nan)

#convert to numeric values and not string
df['User_Score'] = pd.to_numeric(df['User_Score'], errors='coerce')

<StringArray>
[  '8',   nan, '8.3', '8.5', '6.6', '8.4', '8.6', '7.7', '6.3', '7.4', '8.2',
   '9', '7.9', '8.1', '8.7', '7.1', '3.4', '5.3', '4.8', '3.2', '8.9', '6.4',
 '7.8', '7.5', '2.6', '7.2', '9.2',   '7', '7.3', '4.3', '7.6', '5.7',   '5',
 '9.1', '6.5', 'tbd', '8.8', '6.9', '9.4', '6.8']
Length: 40, dtype: str

In [23]:
# find median score
median_user_score = df['User_Score'].median()
print(f'Median User Score: {median_user_score}')

# fill missing values with median
df['User_Score'] = df['User_Score'].fillna(median_user_score)

# validate
print('\nMissing User Scores Remaining:')
print(df['User_Score'].isna().sum())

display(df[['Name', 'User_Score']].head())

Median User Score: 7.5

Missing User Scores Remaining:
0

                       Name  User_Score
0                Wii Sports         8.0
1         Super Mario Bros.         7.5
2            Mario Kart Wii         8.3
3         Wii Sports Resort         8.0
4  Pokemon Red/Pokemon Blue         7.5